### ISSUE TITLE
Update the side image from big logo to featured product

### ISSUE THREAD

**Issue by odarbelaeze** [coreofscience/coreofscience.org#28]
![image](https://user-images.githubusercontent.com/1621518/60475276-33a60580-9c3c-11e9-8b4f-bae3db029ca5.png)

Should look like:

![image](https://user-images.githubusercontent.com/1621518/60475297-491b2f80-9c3c-11e9-91fc-26f91d5603dd.png)

**Comment by jdalzatec** [comment]
We need the featured product image in order to add it to the page.
